-- Add new schema named "app"
CREATE SCHEMA "app";
-- Add new schema named "todo"
CREATE SCHEMA "todo";
-- Modify "moderators" table
ALTER TABLE "public"."moderators" DROP CONSTRAINT "moderators_users_moderator", DROP CONSTRAINT "moderators_users_user";
-- Modify "todo_reminders" table
ALTER TABLE "public"."todo_reminders" DROP CONSTRAINT "todo_reminders_reminders_reminder", DROP CONSTRAINT "todo_reminders_todos_todo";
-- Modify "todos" table
ALTER TABLE "public"."todos" DROP CONSTRAINT "todos_users_todos";
-- Create "moderators" table
CREATE TABLE "app"."moderators" ("user_id" bigint NOT NULL, "moderator_user_id" bigint NOT NULL, PRIMARY KEY ("user_id", "moderator_user_id"));
-- Create index "moderator_moderator_user_id" to table: "moderators"
CREATE INDEX "moderator_moderator_user_id" ON "app"."moderators" ("moderator_user_id");
-- Create index "moderator_user_id" to table: "moderators"
CREATE INDEX "moderator_user_id" ON "app"."moderators" ("user_id");
-- Create "users" table
CREATE TABLE "app"."users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "reminders" table
CREATE TABLE "todo"."reminders" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- Set comment to table: "reminders"
COMMENT ON TABLE "todo"."reminders" IS 'Reminder for a user to take action.';
-- Create "todo_reminders" table
CREATE TABLE "todo"."todo_reminders" ("todo_id" bigint NOT NULL, "reminder_id" bigint NOT NULL, PRIMARY KEY ("todo_id", "reminder_id"));
-- Set comment to table: "todo_reminders"
COMMENT ON TABLE "todo"."todo_reminders" IS 'A join table holding the relationships of todos to reminders';
-- Create "todos" table
CREATE TABLE "todo"."todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "text" character varying NOT NULL, "done_at" timestamptz NULL, "owner_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "todo_owner_id" to table: "todos"
CREATE INDEX "todo_owner_id" ON "todo"."todos" ("owner_id");
-- Modify "moderators" table
ALTER TABLE "app"."moderators" ADD CONSTRAINT "moderators_users_moderator" FOREIGN KEY ("moderator_user_id") REFERENCES "app"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "moderators_users_user" FOREIGN KEY ("user_id") REFERENCES "app"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "todo_reminders" table
ALTER TABLE "todo"."todo_reminders" ADD CONSTRAINT "todo_reminders_reminders_reminder" FOREIGN KEY ("reminder_id") REFERENCES "todo"."reminders" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "todo_reminders_todos_todo" FOREIGN KEY ("todo_id") REFERENCES "todo"."todos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "todos" table
ALTER TABLE "todo"."todos" ADD CONSTRAINT "todos_users_todos" FOREIGN KEY ("owner_id") REFERENCES "app"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Drop "moderators" table
DROP TABLE "public"."moderators";
-- Drop "reminders" table
DROP TABLE "public"."reminders";
-- Drop "todo_reminders" table
DROP TABLE "public"."todo_reminders";
-- Drop "todos" table
DROP TABLE "public"."todos";
-- Drop "users" table
DROP TABLE "public"."users";
