-- Create "reminders" table
CREATE TABLE "reminders" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- Set comment to table: "reminders"
COMMENT ON TABLE "reminders" IS 'Reminder for a user to take action.';
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "text" character varying NOT NULL, "done_at" timestamptz NULL, "owner_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "todos_users_todos" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "todo_owner_id" to table: "todos"
CREATE INDEX "todo_owner_id" ON "todos" ("owner_id");
-- Create "todo_reminders" table
CREATE TABLE "todo_reminders" ("todo_id" bigint NOT NULL, "reminder_id" bigint NOT NULL, PRIMARY KEY ("todo_id", "reminder_id"), CONSTRAINT "todo_reminders_reminders_reminder" FOREIGN KEY ("reminder_id") REFERENCES "reminders" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "todo_reminders_todos_todo" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Set comment to table: "todo_reminders"
COMMENT ON TABLE "todo_reminders" IS 'A join table holding the relationships of todos to reminders';
