// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Moderator is the predicate function for moderator builders.
type Moderator func(*sql.Selector)

// PeoplePartner is the predicate function for peoplepartner builders.
type PeoplePartner func(*sql.Selector)

// Reminder is the predicate function for reminder builders.
type Reminder func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// TodoReminder is the predicate function for todoreminder builders.
type TodoReminder func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
