// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"example/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"

	"example/internal/ent/internal"
	"example/internal/ent/moderator"
)

// ModeratorDelete is the builder for deleting a Moderator entity.
type ModeratorDelete struct {
	config
	hooks    []Hook
	mutation *ModeratorMutation
}

// Where appends a list predicates to the ModeratorDelete builder.
func (_d *ModeratorDelete) Where(ps ...predicate.Moderator) *ModeratorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModeratorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModeratorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModeratorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(moderator.Table, nil)
	_spec.Node.Schema = _d.schemaConfig.Moderator
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModeratorDeleteOne is the builder for deleting a single Moderator entity.
type ModeratorDeleteOne struct {
	_d *ModeratorDelete
}

// Where appends a list predicates to the ModeratorDelete builder.
func (_d *ModeratorDeleteOne) Where(ps ...predicate.Moderator) *ModeratorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModeratorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moderator.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModeratorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
