// Code generated by ent, DO NOT EDIT.

package ent

import (
	"example/internal/ent/peoplepartner"
	"example/internal/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PeoplePartner is the model entity for the PeoplePartner schema.
type PeoplePartner struct {
	config `json:"-"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// PeoplePartnerUserID holds the value of the "people_partner_user_id" field.
	PeoplePartnerUserID int `json:"people_partner_user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PeoplePartnerQuery when eager-loading is set.
	Edges        PeoplePartnerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PeoplePartnerEdges holds the relations/edges for other nodes in the graph.
type PeoplePartnerEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// PeoplePartner holds the value of the people_partner edge.
	PeoplePartner *User `json:"people_partner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PeoplePartnerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PeoplePartnerOrErr returns the PeoplePartner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PeoplePartnerEdges) PeoplePartnerOrErr() (*User, error) {
	if e.PeoplePartner != nil {
		return e.PeoplePartner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "people_partner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PeoplePartner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case peoplepartner.FieldUserID, peoplepartner.FieldPeoplePartnerUserID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PeoplePartner fields.
func (_m *PeoplePartner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case peoplepartner.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case peoplepartner.FieldPeoplePartnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field people_partner_user_id", values[i])
			} else if value.Valid {
				_m.PeoplePartnerUserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PeoplePartner.
// This includes values selected through modifiers, order, etc.
func (_m *PeoplePartner) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PeoplePartner entity.
func (_m *PeoplePartner) QueryUser() *UserQuery {
	return NewPeoplePartnerClient(_m.config).QueryUser(_m)
}

// QueryPeoplePartner queries the "people_partner" edge of the PeoplePartner entity.
func (_m *PeoplePartner) QueryPeoplePartner() *UserQuery {
	return NewPeoplePartnerClient(_m.config).QueryPeoplePartner(_m)
}

// Update returns a builder for updating this PeoplePartner.
// Note that you need to call PeoplePartner.Unwrap() before calling this method if this PeoplePartner
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PeoplePartner) Update() *PeoplePartnerUpdateOne {
	return NewPeoplePartnerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PeoplePartner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PeoplePartner) Unwrap() *PeoplePartner {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PeoplePartner is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PeoplePartner) String() string {
	var builder strings.Builder
	builder.WriteString("PeoplePartner(")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("people_partner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeoplePartnerUserID))
	builder.WriteByte(')')
	return builder.String()
}

// PeoplePartners is a parsable slice of PeoplePartner.
type PeoplePartners []*PeoplePartner
