// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"example/internal/ent/predicate"
	"example/internal/ent/todoreminder"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// TodoReminderDelete is the builder for deleting a TodoReminder entity.
type TodoReminderDelete struct {
	config
	hooks    []Hook
	mutation *TodoReminderMutation
}

// Where appends a list predicates to the TodoReminderDelete builder.
func (_d *TodoReminderDelete) Where(ps ...predicate.TodoReminder) *TodoReminderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TodoReminderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoReminderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TodoReminderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todoreminder.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TodoReminderDeleteOne is the builder for deleting a single TodoReminder entity.
type TodoReminderDeleteOne struct {
	_d *TodoReminderDelete
}

// Where appends a list predicates to the TodoReminderDelete builder.
func (_d *TodoReminderDeleteOne) Where(ps ...predicate.TodoReminder) *TodoReminderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TodoReminderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todoreminder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoReminderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
