// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"example/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"example/internal/ent/internal"
	"example/internal/ent/todototodogroupassociation"
)

// TodoToTodoGroupAssociationDelete is the builder for deleting a TodoToTodoGroupAssociation entity.
type TodoToTodoGroupAssociationDelete struct {
	config
	hooks    []Hook
	mutation *TodoToTodoGroupAssociationMutation
}

// Where appends a list predicates to the TodoToTodoGroupAssociationDelete builder.
func (_d *TodoToTodoGroupAssociationDelete) Where(ps ...predicate.TodoToTodoGroupAssociation) *TodoToTodoGroupAssociationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TodoToTodoGroupAssociationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoToTodoGroupAssociationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TodoToTodoGroupAssociationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todototodogroupassociation.Table, sqlgraph.NewFieldSpec(todototodogroupassociation.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.TodoToTodoGroupAssociation
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TodoToTodoGroupAssociationDeleteOne is the builder for deleting a single TodoToTodoGroupAssociation entity.
type TodoToTodoGroupAssociationDeleteOne struct {
	_d *TodoToTodoGroupAssociationDelete
}

// Where appends a list predicates to the TodoToTodoGroupAssociationDelete builder.
func (_d *TodoToTodoGroupAssociationDeleteOne) Where(ps ...predicate.TodoToTodoGroupAssociation) *TodoToTodoGroupAssociationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TodoToTodoGroupAssociationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todototodogroupassociation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoToTodoGroupAssociationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
