// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"example/internal/ent/predicate"
	"example/internal/ent/todo"
	"example/internal/ent/todogroup"
	"example/internal/ent/todototodogroupassociation"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"example/internal/ent/internal"
)

// TodoGroupQuery is the builder for querying TodoGroup entities.
type TodoGroupQuery struct {
	config
	ctx                   *QueryContext
	order                 []todogroup.OrderOption
	inters                []Interceptor
	predicates            []predicate.TodoGroup
	withTodos             *TodoQuery
	withGroupedTodos      *TodoToTodoGroupAssociationQuery
	loadTotal             []func(context.Context, []*TodoGroup) error
	modifiers             []func(*sql.Selector)
	withNamedTodos        map[string]*TodoQuery
	withNamedGroupedTodos map[string]*TodoToTodoGroupAssociationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TodoGroupQuery builder.
func (_q *TodoGroupQuery) Where(ps ...predicate.TodoGroup) *TodoGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TodoGroupQuery) Limit(limit int) *TodoGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TodoGroupQuery) Offset(offset int) *TodoGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TodoGroupQuery) Unique(unique bool) *TodoGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TodoGroupQuery) Order(o ...todogroup.OrderOption) *TodoGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTodos chains the current query on the "todos" edge.
func (_q *TodoGroupQuery) QueryTodos() *TodoQuery {
	query := (&TodoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todogroup.Table, todogroup.FieldID, selector),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, todogroup.TodosTable, todogroup.TodosPrimaryKey...),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.Todo
		step.Edge.Schema = schemaConfig.TodoToTodoGroupAssociation
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroupedTodos chains the current query on the "grouped_todos" edge.
func (_q *TodoGroupQuery) QueryGroupedTodos() *TodoToTodoGroupAssociationQuery {
	query := (&TodoToTodoGroupAssociationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todogroup.Table, todogroup.FieldID, selector),
			sqlgraph.To(todototodogroupassociation.Table, todototodogroupassociation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, todogroup.GroupedTodosTable, todogroup.GroupedTodosColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.TodoToTodoGroupAssociation
		step.Edge.Schema = schemaConfig.TodoToTodoGroupAssociation
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TodoGroup entity from the query.
// Returns a *NotFoundError when no TodoGroup was found.
func (_q *TodoGroupQuery) First(ctx context.Context) (*TodoGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{todogroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TodoGroupQuery) FirstX(ctx context.Context) *TodoGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TodoGroup ID from the query.
// Returns a *NotFoundError when no TodoGroup ID was found.
func (_q *TodoGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{todogroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TodoGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TodoGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TodoGroup entity is found.
// Returns a *NotFoundError when no TodoGroup entities are found.
func (_q *TodoGroupQuery) Only(ctx context.Context) (*TodoGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{todogroup.Label}
	default:
		return nil, &NotSingularError{todogroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TodoGroupQuery) OnlyX(ctx context.Context) *TodoGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TodoGroup ID in the query.
// Returns a *NotSingularError when more than one TodoGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TodoGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{todogroup.Label}
	default:
		err = &NotSingularError{todogroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TodoGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TodoGroups.
func (_q *TodoGroupQuery) All(ctx context.Context) ([]*TodoGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TodoGroup, *TodoGroupQuery]()
	return withInterceptors[[]*TodoGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TodoGroupQuery) AllX(ctx context.Context) []*TodoGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TodoGroup IDs.
func (_q *TodoGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(todogroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TodoGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TodoGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TodoGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TodoGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TodoGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TodoGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TodoGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TodoGroupQuery) Clone() *TodoGroupQuery {
	if _q == nil {
		return nil
	}
	return &TodoGroupQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]todogroup.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.TodoGroup{}, _q.predicates...),
		withTodos:        _q.withTodos.Clone(),
		withGroupedTodos: _q.withGroupedTodos.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTodos tells the query-builder to eager-load the nodes that are connected to
// the "todos" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TodoGroupQuery) WithTodos(opts ...func(*TodoQuery)) *TodoGroupQuery {
	query := (&TodoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTodos = query
	return _q
}

// WithGroupedTodos tells the query-builder to eager-load the nodes that are connected to
// the "grouped_todos" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TodoGroupQuery) WithGroupedTodos(opts ...func(*TodoToTodoGroupAssociationQuery)) *TodoGroupQuery {
	query := (&TodoToTodoGroupAssociationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroupedTodos = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TodoGroup.Query().
//		GroupBy(todogroup.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TodoGroupQuery) GroupBy(field string, fields ...string) *TodoGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TodoGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = todogroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TodoGroup.Query().
//		Select(todogroup.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *TodoGroupQuery) Select(fields ...string) *TodoGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TodoGroupSelect{TodoGroupQuery: _q}
	sbuild.label = todogroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TodoGroupSelect configured with the given aggregations.
func (_q *TodoGroupQuery) Aggregate(fns ...AggregateFunc) *TodoGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TodoGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !todogroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TodoGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TodoGroup, error) {
	var (
		nodes       = []*TodoGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTodos != nil,
			_q.withGroupedTodos != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TodoGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TodoGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.TodoGroup
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTodos; query != nil {
		if err := _q.loadTodos(ctx, query, nodes,
			func(n *TodoGroup) { n.Edges.Todos = []*Todo{} },
			func(n *TodoGroup, e *Todo) { n.Edges.Todos = append(n.Edges.Todos, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroupedTodos; query != nil {
		if err := _q.loadGroupedTodos(ctx, query, nodes,
			func(n *TodoGroup) { n.Edges.GroupedTodos = []*TodoToTodoGroupAssociation{} },
			func(n *TodoGroup, e *TodoToTodoGroupAssociation) {
				n.Edges.GroupedTodos = append(n.Edges.GroupedTodos, e)
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedTodos {
		if err := _q.loadTodos(ctx, query, nodes,
			func(n *TodoGroup) { n.appendNamedTodos(name) },
			func(n *TodoGroup, e *Todo) { n.appendNamedTodos(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedGroupedTodos {
		if err := _q.loadGroupedTodos(ctx, query, nodes,
			func(n *TodoGroup) { n.appendNamedGroupedTodos(name) },
			func(n *TodoGroup, e *TodoToTodoGroupAssociation) { n.appendNamedGroupedTodos(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TodoGroupQuery) loadTodos(ctx context.Context, query *TodoQuery, nodes []*TodoGroup, init func(*TodoGroup), assign func(*TodoGroup, *Todo)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*TodoGroup)
	nids := make(map[int]map[*TodoGroup]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(todogroup.TodosTable)
		joinT.Schema(_q.schemaConfig.TodoToTodoGroupAssociation)
		s.Join(joinT).On(s.C(todo.FieldID), joinT.C(todogroup.TodosPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(todogroup.TodosPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(todogroup.TodosPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*TodoGroup]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Todo](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "todos" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *TodoGroupQuery) loadGroupedTodos(ctx context.Context, query *TodoToTodoGroupAssociationQuery, nodes []*TodoGroup, init func(*TodoGroup), assign func(*TodoGroup, *TodoToTodoGroupAssociation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*TodoGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(todototodogroupassociation.FieldTodoGroupReallyReallyLongIdentifier)
	}
	query.Where(predicate.TodoToTodoGroupAssociation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(todogroup.GroupedTodosColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TodoGroupReallyReallyLongIdentifier
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "todo_group_really_really_long_identifier" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TodoGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.TodoGroup
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TodoGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(todogroup.Table, todogroup.Columns, sqlgraph.NewFieldSpec(todogroup.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todogroup.FieldID)
		for i := range fields {
			if fields[i] != todogroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TodoGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(todogroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = todogroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.TodoGroup)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *TodoGroupQuery) Modify(modifiers ...func(s *sql.Selector)) *TodoGroupSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedTodos tells the query-builder to eager-load the nodes that are connected to the "todos"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *TodoGroupQuery) WithNamedTodos(name string, opts ...func(*TodoQuery)) *TodoGroupQuery {
	query := (&TodoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedTodos == nil {
		_q.withNamedTodos = make(map[string]*TodoQuery)
	}
	_q.withNamedTodos[name] = query
	return _q
}

// WithNamedGroupedTodos tells the query-builder to eager-load the nodes that are connected to the "grouped_todos"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *TodoGroupQuery) WithNamedGroupedTodos(name string, opts ...func(*TodoToTodoGroupAssociationQuery)) *TodoGroupQuery {
	query := (&TodoToTodoGroupAssociationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedGroupedTodos == nil {
		_q.withNamedGroupedTodos = make(map[string]*TodoToTodoGroupAssociationQuery)
	}
	_q.withNamedGroupedTodos[name] = query
	return _q
}

// TodoGroupGroupBy is the group-by builder for TodoGroup entities.
type TodoGroupGroupBy struct {
	selector
	build *TodoGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TodoGroupGroupBy) Aggregate(fns ...AggregateFunc) *TodoGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TodoGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoGroupQuery, *TodoGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TodoGroupGroupBy) sqlScan(ctx context.Context, root *TodoGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TodoGroupSelect is the builder for selecting fields of TodoGroup entities.
type TodoGroupSelect struct {
	*TodoGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TodoGroupSelect) Aggregate(fns ...AggregateFunc) *TodoGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TodoGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoGroupQuery, *TodoGroupSelect](ctx, _s.TodoGroupQuery, _s, _s.inters, v)
}

func (_s *TodoGroupSelect) sqlScan(ctx context.Context, root *TodoGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *TodoGroupSelect) Modify(modifiers ...func(s *sql.Selector)) *TodoGroupSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
