// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"example/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"example/internal/ent/internal"
	"example/internal/ent/todogroup"
)

// TodoGroupDelete is the builder for deleting a TodoGroup entity.
type TodoGroupDelete struct {
	config
	hooks    []Hook
	mutation *TodoGroupMutation
}

// Where appends a list predicates to the TodoGroupDelete builder.
func (_d *TodoGroupDelete) Where(ps ...predicate.TodoGroup) *TodoGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TodoGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TodoGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todogroup.Table, sqlgraph.NewFieldSpec(todogroup.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.TodoGroup
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TodoGroupDeleteOne is the builder for deleting a single TodoGroup entity.
type TodoGroupDeleteOne struct {
	_d *TodoGroupDelete
}

// Where appends a list predicates to the TodoGroupDelete builder.
func (_d *TodoGroupDeleteOne) Where(ps ...predicate.TodoGroup) *TodoGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TodoGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todogroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
