// Code generated by ent, DO NOT EDIT.

package todototodogroupassociation

import (
	"example/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"

	"example/internal/ent/internal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldUpdatedAt, v))
}

// TodoID applies equality check predicate on the "todo_id" field. It's identical to TodoIDEQ.
func TodoID(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldTodoID, v))
}

// TodoGroupReallyReallyLongIdentifier applies equality check predicate on the "todo_group_really_really_long_identifier" field. It's identical to TodoGroupReallyReallyLongIdentifierEQ.
func TodoGroupReallyReallyLongIdentifier(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldTodoGroupReallyReallyLongIdentifier, v))
}

// AssigneeID applies equality check predicate on the "assignee_id" field. It's identical to AssigneeIDEQ.
func AssigneeID(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldAssigneeID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLTE(FieldUpdatedAt, v))
}

// TodoIDEQ applies the EQ predicate on the "todo_id" field.
func TodoIDEQ(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldTodoID, v))
}

// TodoIDNEQ applies the NEQ predicate on the "todo_id" field.
func TodoIDNEQ(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNEQ(FieldTodoID, v))
}

// TodoIDIn applies the In predicate on the "todo_id" field.
func TodoIDIn(vs ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldIn(FieldTodoID, vs...))
}

// TodoIDNotIn applies the NotIn predicate on the "todo_id" field.
func TodoIDNotIn(vs ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNotIn(FieldTodoID, vs...))
}

// TodoGroupReallyReallyLongIdentifierEQ applies the EQ predicate on the "todo_group_really_really_long_identifier" field.
func TodoGroupReallyReallyLongIdentifierEQ(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldTodoGroupReallyReallyLongIdentifier, v))
}

// TodoGroupReallyReallyLongIdentifierNEQ applies the NEQ predicate on the "todo_group_really_really_long_identifier" field.
func TodoGroupReallyReallyLongIdentifierNEQ(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNEQ(FieldTodoGroupReallyReallyLongIdentifier, v))
}

// TodoGroupReallyReallyLongIdentifierIn applies the In predicate on the "todo_group_really_really_long_identifier" field.
func TodoGroupReallyReallyLongIdentifierIn(vs ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldIn(FieldTodoGroupReallyReallyLongIdentifier, vs...))
}

// TodoGroupReallyReallyLongIdentifierNotIn applies the NotIn predicate on the "todo_group_really_really_long_identifier" field.
func TodoGroupReallyReallyLongIdentifierNotIn(vs ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNotIn(FieldTodoGroupReallyReallyLongIdentifier, vs...))
}

// AssigneeIDEQ applies the EQ predicate on the "assignee_id" field.
func AssigneeIDEQ(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldEQ(FieldAssigneeID, v))
}

// AssigneeIDNEQ applies the NEQ predicate on the "assignee_id" field.
func AssigneeIDNEQ(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNEQ(FieldAssigneeID, v))
}

// AssigneeIDIn applies the In predicate on the "assignee_id" field.
func AssigneeIDIn(vs ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldIn(FieldAssigneeID, vs...))
}

// AssigneeIDNotIn applies the NotIn predicate on the "assignee_id" field.
func AssigneeIDNotIn(vs ...int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldNotIn(FieldAssigneeID, vs...))
}

// AssigneeIDGT applies the GT predicate on the "assignee_id" field.
func AssigneeIDGT(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGT(FieldAssigneeID, v))
}

// AssigneeIDGTE applies the GTE predicate on the "assignee_id" field.
func AssigneeIDGTE(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldGTE(FieldAssigneeID, v))
}

// AssigneeIDLT applies the LT predicate on the "assignee_id" field.
func AssigneeIDLT(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLT(FieldAssigneeID, v))
}

// AssigneeIDLTE applies the LTE predicate on the "assignee_id" field.
func AssigneeIDLTE(v int) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.FieldLTE(FieldAssigneeID, v))
}

// HasTodo applies the HasEdge predicate on the "todo" edge.
func HasTodo() predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TodoTable, TodoColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Todo
		step.Edge.Schema = schemaConfig.TodoToTodoGroupAssociation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTodoWith applies the HasEdge predicate on the "todo" edge with a given conditions (other predicates).
func HasTodoWith(preds ...predicate.Todo) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(func(s *sql.Selector) {
		step := newTodoStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Todo
		step.Edge.Schema = schemaConfig.TodoToTodoGroupAssociation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTodoGroup applies the HasEdge predicate on the "todo_group" edge.
func HasTodoGroup() predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TodoGroupTable, TodoGroupColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.TodoGroup
		step.Edge.Schema = schemaConfig.TodoToTodoGroupAssociation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTodoGroupWith applies the HasEdge predicate on the "todo_group" edge with a given conditions (other predicates).
func HasTodoGroupWith(preds ...predicate.TodoGroup) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(func(s *sql.Selector) {
		step := newTodoGroupStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.TodoGroup
		step.Edge.Schema = schemaConfig.TodoToTodoGroupAssociation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TodoToTodoGroupAssociation) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TodoToTodoGroupAssociation) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TodoToTodoGroupAssociation) predicate.TodoToTodoGroupAssociation {
	return predicate.TodoToTodoGroupAssociation(sql.NotPredicates(p))
}
