// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"

	"example/internal/ent"

	"entgo.io/ent/entql"
	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns a formatted wrapped Allow decision.
func Allowf(format string, a ...any) error {
	return privacy.Allowf(format, a...)
}

// Denyf returns a formatted wrapped Deny decision.
func Denyf(format string, a ...any) error {
	return privacy.Denyf(format, a...)
}

// Skipf returns a formatted wrapped Skip decision.
func Skipf(format string, a ...any) error {
	return privacy.Skipf(format, a...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
	// MutationRuleFunc type is an adapter which allows the use of
	// ordinary functions as mutation rules.
	MutationRuleFunc = privacy.MutationRuleFunc

	// QueryMutationRule is an interface which groups query and mutation rules.
	QueryMutationRule = privacy.QueryMutationRule
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, ent.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	return f(ctx, q)
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return privacy.AlwaysAllowRule()
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return privacy.AlwaysDenyRule()
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return privacy.ContextQueryMutationRule(eval)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op ent.Op) MutationRule {
	return privacy.OnMutationOperation(rule, op)
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op ent.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m ent.Mutation) error {
		return Denyf("ent/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The ModeratorQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ModeratorQueryRuleFunc func(context.Context, *ent.ModeratorQuery) error

// EvalQuery return f(ctx, q).
func (f ModeratorQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ModeratorQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ModeratorQuery", q)
}

// The ModeratorMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ModeratorMutationRuleFunc func(context.Context, *ent.ModeratorMutation) error

// EvalMutation calls f(ctx, m).
func (f ModeratorMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ModeratorMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ModeratorMutation", m)
}

// The ReminderQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ReminderQueryRuleFunc func(context.Context, *ent.ReminderQuery) error

// EvalQuery return f(ctx, q).
func (f ReminderQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ReminderQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ReminderQuery", q)
}

// The ReminderMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ReminderMutationRuleFunc func(context.Context, *ent.ReminderMutation) error

// EvalMutation calls f(ctx, m).
func (f ReminderMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ReminderMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ReminderMutation", m)
}

// The TodoQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TodoQueryRuleFunc func(context.Context, *ent.TodoQuery) error

// EvalQuery return f(ctx, q).
func (f TodoQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TodoQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TodoQuery", q)
}

// The TodoMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TodoMutationRuleFunc func(context.Context, *ent.TodoMutation) error

// EvalMutation calls f(ctx, m).
func (f TodoMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TodoMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TodoMutation", m)
}

// The TodoGroupQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TodoGroupQueryRuleFunc func(context.Context, *ent.TodoGroupQuery) error

// EvalQuery return f(ctx, q).
func (f TodoGroupQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TodoGroupQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TodoGroupQuery", q)
}

// The TodoGroupMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TodoGroupMutationRuleFunc func(context.Context, *ent.TodoGroupMutation) error

// EvalMutation calls f(ctx, m).
func (f TodoGroupMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TodoGroupMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TodoGroupMutation", m)
}

// The TodoReminderQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TodoReminderQueryRuleFunc func(context.Context, *ent.TodoReminderQuery) error

// EvalQuery return f(ctx, q).
func (f TodoReminderQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TodoReminderQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TodoReminderQuery", q)
}

// The TodoReminderMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TodoReminderMutationRuleFunc func(context.Context, *ent.TodoReminderMutation) error

// EvalMutation calls f(ctx, m).
func (f TodoReminderMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TodoReminderMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TodoReminderMutation", m)
}

// The TodoToTodoGroupAssociationQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TodoToTodoGroupAssociationQueryRuleFunc func(context.Context, *ent.TodoToTodoGroupAssociationQuery) error

// EvalQuery return f(ctx, q).
func (f TodoToTodoGroupAssociationQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TodoToTodoGroupAssociationQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TodoToTodoGroupAssociationQuery", q)
}

// The TodoToTodoGroupAssociationMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TodoToTodoGroupAssociationMutationRuleFunc func(context.Context, *ent.TodoToTodoGroupAssociationMutation) error

// EvalMutation calls f(ctx, m).
func (f TodoToTodoGroupAssociationMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TodoToTodoGroupAssociationMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TodoToTodoGroupAssociationMutation", m)
}

// The UserQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserQueryRuleFunc func(context.Context, *ent.UserQuery) error

// EvalQuery return f(ctx, q).
func (f UserQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.UserQuery", q)
}

// The UserMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserMutationRuleFunc func(context.Context, *ent.UserMutation) error

// EvalMutation calls f(ctx, m).
func (f UserMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.UserMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.UserMutation", m)
}

type (
	// Filter is the interface that wraps the Where function
	// for filtering nodes in queries and mutations.
	Filter interface {
		// Where applies a filter on the executed query/mutation.
		Where(entql.P)
	}

	// The FilterFunc type is an adapter that allows the use of ordinary
	// functions as filters for query and mutation types.
	FilterFunc func(context.Context, Filter) error
)

// EvalQuery calls f(ctx, q) if the query implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	fr, err := queryFilter(q)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

// EvalMutation calls f(ctx, q) if the mutation implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	fr, err := mutationFilter(m)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

var _ QueryMutationRule = FilterFunc(nil)

func queryFilter(q ent.Query) (Filter, error) {
	switch q := q.(type) {
	case *ent.ModeratorQuery:
		return q.Filter(), nil
	case *ent.ReminderQuery:
		return q.Filter(), nil
	case *ent.TodoQuery:
		return q.Filter(), nil
	case *ent.TodoGroupQuery:
		return q.Filter(), nil
	case *ent.TodoReminderQuery:
		return q.Filter(), nil
	case *ent.TodoToTodoGroupAssociationQuery:
		return q.Filter(), nil
	case *ent.UserQuery:
		return q.Filter(), nil
	default:
		return nil, Denyf("ent/privacy: unexpected query type %T for query filter", q)
	}
}

func mutationFilter(m ent.Mutation) (Filter, error) {
	switch m := m.(type) {
	case *ent.ModeratorMutation:
		return m.Filter(), nil
	case *ent.ReminderMutation:
		return m.Filter(), nil
	case *ent.TodoMutation:
		return m.Filter(), nil
	case *ent.TodoGroupMutation:
		return m.Filter(), nil
	case *ent.TodoReminderMutation:
		return m.Filter(), nil
	case *ent.TodoToTodoGroupAssociationMutation:
		return m.Filter(), nil
	case *ent.UserMutation:
		return m.Filter(), nil
	default:
		return nil, Denyf("ent/privacy: unexpected mutation type %T for mutation filter", m)
	}
}
