// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RemindersColumns holds the columns for the "reminders" table.
	RemindersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
	}
	// RemindersTable holds the schema information for the "reminders" table.
	RemindersTable = &schema.Table{
		Name:       "reminders",
		Comment:    "Reminder for a user to take action.",
		Columns:    RemindersColumns,
		PrimaryKey: []*schema.Column{RemindersColumns[0]},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString, Size: 255},
		{Name: "done_at", Type: field.TypeTime, Nullable: true},
		{Name: "owner_id", Type: field.TypeInt},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "todos_users_todos",
				Columns:    []*schema.Column{TodosColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "todo_owner_id",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[3]},
			},
		},
	}
	// TodoRemindersColumns holds the columns for the "todo_reminders" table.
	TodoRemindersColumns = []*schema.Column{
		{Name: "todo_id", Type: field.TypeInt},
		{Name: "reminder_id", Type: field.TypeInt},
	}
	// TodoRemindersTable holds the schema information for the "todo_reminders" table.
	TodoRemindersTable = &schema.Table{
		Name:       "todo_reminders",
		Comment:    "A join table holding the relationships of todos to reminders",
		Columns:    TodoRemindersColumns,
		PrimaryKey: []*schema.Column{TodoRemindersColumns[0], TodoRemindersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "todo_reminders_todos_todo",
				Columns:    []*schema.Column{TodoRemindersColumns[0]},
				RefColumns: []*schema.Column{TodosColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "todo_reminders_reminders_reminder",
				Columns:    []*schema.Column{TodoRemindersColumns[1]},
				RefColumns: []*schema.Column{RemindersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RemindersTable,
		TodosTable,
		TodoRemindersTable,
		UsersTable,
	}
)

func init() {
	RemindersTable.Annotation = &entsql.Annotation{
		Table:          "reminders",
		IncrementStart: func(i int) *int { return &i }(8589934592),
	}
	TodosTable.ForeignKeys[0].RefTable = UsersTable
	TodosTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(4294967296),
	}
	TodoRemindersTable.ForeignKeys[0].RefTable = TodosTable
	TodoRemindersTable.ForeignKeys[1].RefTable = RemindersTable
	TodoRemindersTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(12884901888),
	}
	UsersTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(0),
	}
}
